pr: none
trigger: none
schedules:
- cron: "0 3 * * 2,5"
  displayName: Workday morning NuGet PR
  branches:
    include:
      - master
  always: true

resources:
  repositories:
  - repository: QueueReceiverService # The name used to reference this repository in the checkout step
    type: github
    name: equinor/procosys-queue-reciver-service
    endpoint: procosys - github
  - repository: AuthAccessTriggerFunction # The name used to reference this repository in the checkout step
    type: github
    name: equinor/procosys-auth-access-trigger-function
    endpoint: procosys - github

pool:
  vmImage: 'ubuntu-latest'

stages:

### Queue Receiver Service ###
- stage: QueueReceiverService
  displayName: QueueReceiverService
  dependsOn: []
  jobs:
  - job: QueueReceiverService
    steps:
    - checkout: QueueReceiverService
    - task: nukeeper.nukeeper.nukeeper.NuKeeper@0
      displayName: NuKeeper
      inputs:
        gitHubConnection: 'procosys - github'
        arguments: '--age 7d --change Major --maxpackageupdates 100 --consolidate --fork PreferSingleRepository'

### Auth Access Trigger Function ###
- stage: AuthAccessTriggerFunction
  displayName: AuthAccessTriggerFunction
  dependsOn: []
  jobs:
  - job: AuthAccessTriggerFunction
    steps:
    - checkout: AuthAccessTriggerFunction
    - task: nukeeper.nukeeper.nukeeper.NuKeeper@0
      displayName: NuKeeper
      inputs:
        gitHubConnection: 'procosys - github'
        arguments: '--age 7d --change Major --maxpackageupdates 100 --consolidate --fork PreferSingleRepository'
