pr: none
trigger: none
schedules:
- cron: "23 8 * * 1-5"
  displayName: Workday morning NuGet PR
  always: true

resources:
  repositories:
  - repository: Library # The name used to reference this repository in the checkout step
    type: github
    name: equinor/procosys-library-api
    endpoint: procosys - github

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Library
  displayName: Library
  steps:
  - checkout: Library
  - task: nukeeper.nukeeper.nukeeper.NuKeeper@0
    displayName: NuKeeper
    inputs:
      gitHubConnection: 'procosys - github'
      arguments: '--age 0 --change Major --maxpackageupdates 100 --consolidate --fork PreferSingleRepository'
      targetFolder: src